<?php

$labels = array();
$labels['null'] = ' ';
$labels['title'] = 'Archiver les courriels de ce dossier';
$labels['archive'] = 'Archiver';
$labels['date'] = 'Soit jusqu'au : ';
$labels['nb_jours'] = 'Messages de plus de  : ';
$labels['jours'] = 'jours';
$labels['buttontext'] = 'Archiver';
$labels['buttontitle'] = 'Archiver ce courriel';
$labels['description'] = "Comment fonctionne l'archivage : Sélectionnez un nombre de jours ou une date, tous les messages du dossier courant antérieur à cette date seront téléchargés sur votre poste. Ces messages ne seront pas supprimés de votre messagerie mais déplacés dans un dossier Messages archivés. Une fois que l'archive téléchargée vous convient, vous pouvez supprimer les messages contenus dans Messages archivés pour libérer de la place.";

?>
